In [1]:
import numpy as np

In [2]:
arr=np.array([13,9,2003])

In [3]:
a1=arr[1]

In [4]:
print(a1)

9


In [6]:
#tao mang 2 chieu
matran=np.array([[13,9,2003],[5,7,1997],[5,5,2004]])
print(matran)

[[  13    9 2003]
 [   5    7 1997]
 [   5    5 2004]]


In [12]:
a2=matran[1,2]

In [13]:
print(a2)

1997


In [15]:
#tao mang so 0
a=np.zeros(3)

In [16]:
print(a)

[0. 0. 0.]


In [17]:
a=np.ones(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [18]:
#tao mang tu 0 cho den 9
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
#tao mang 
a=np.empty(6)
print(a)

[1. 1. 1. 1. 1. 1.]


In [20]:
#tao mang voi gom cac phan tu voi khoang cach deu nhau
a=np.linspace(0,10,num=5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
#xac dinh kieu du lieu
a=np.ones(5,dtype=np.int64)
a

array([1, 1, 1, 1, 1])

In [24]:
# Thêm, xóa, sắp xếp mảng
#tao mang ban dau
arr=np.array([4,8,5,2,6,1])
print(arr)

[4 8 5 2 6 1]


In [25]:
arr=np.sort(arr)
print(arr)

[1 2 4 5 6 8]


In [27]:
#sap sep nguoc
arr=np.sort(arr)[::-1]
print(arr)

[8 6 5 4 2 1]


In [29]:
#them phan tu vao mang
arr=np.append(arr,2003)
print(arr)

[   8    6    5    4    2    1 2003]


In [30]:
#xoa 1 vi tri nao do trong mang
arr=np.delete(arr,2)
print(arr)

[   8    6    4    2    1 2003]


In [31]:
# Tạo một mảng 2 chiều
arr = np.array([[13, 9, 2003],
                [5, 7, 1997],
                [9, 7, 2005]])

sap_xep_theo_hang = np.sort(arr, axis=1) # tăng dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) # tăng dần
print(sap_xep_theo_cot)

[[   9   13 2003]
 [   5    7 1997]
 [   7    9 2005]]
[[   5    7 1997]
 [   9    7 2003]
 [  13    9 2005]]


In [32]:
# Tạo một mảng 2 chiều
arr = np.array([[13, 9, 2003],
                [5, 7, 1997],
                [9, 7, 2005]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) # giảm dần
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) # giảm dần
print(sap_xep_theo_cot)

[[2003   13    9]
 [1997    7    5]
 [2005    9    7]]
[[  13    9 2005]
 [   9    7 2003]
 [   5    7 1997]]


In [33]:
# Tạo một mảng 2D
arr = np.array([[100, 20, 329], [435, 575, 136]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  # Số chiều (2 chiều)
kich_thuoc = arr.size  # Kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # Hình dạng (số hàng x số cột, (2, 3))

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [35]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([13, 9, 2003, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[  13.    9. 2003.    4.    5.]


In [38]:
# Thay đổi hình dạng của mảng
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [39]:
reshaped_arr = reshaped_arr.flatten() # Chuyển thành mảng 1 chiều
print(reshaped_arr)

[1 2 3 4 5 6]


In [40]:
# Cắt lát mảng
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]  # 1 2 3 4
print(sub_arr)

sub_arr = arr[-2:]  # 4 5 
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [41]:
# Chuyển vị mảng
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [42]:
# Nối mảng
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [43]:
# II. Hàm tính tổng (Sum)
# - Hàm numpy.sum() cho phép tính tổng các phần tử trong mảng.
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng của mảng arr:", total)

# III. Hàm tính trung bình (Mean)
# - Hàm numpy.mean() tính giá trị trung bình của các phần tử trong mảng.
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

# IV. Hàm tìm giá trị lớn nhất và nhỏ nhất (Max và Min)
# - Hàm numpy.max() và numpy.min() dùng để tìm giá trị lớn nhất và nhỏ nhất trong mảng.
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

# V. Hàm tính độ lệch chuẩn (Standard Deviation)
# - Hàm numpy.std() tính độ lệch chuẩn của mảng, đo lường mức độ phân tán của dữ liệu.
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

# VI. Hàm tính phương sai (Variance)
# - Hàm numpy.var() tính phương sai của mảng, đo lường mức độ biến thiên của dữ liệu.
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

# VII. Hàm tính tổng tích chập (Dot Product)
# - Hàm numpy.dot() tính tổng tích chập của hai mảng (vector).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 15
Giá trị trung bình của mảng arr: 3.0
Giá trị lớn nhất trong mảng arr: 5
Giá trị nhỏ nhất trong mảng arr: 1
Độ lệch chuẩn của mảng arr: 1.4142135623730951
Phương sai của mảng arr: 2.0
Tổng tích chập của arr1 và arr2: 32
